### ISSUE TITLE
GZDoom Builder throws a fit when attempting to edit the MAPINFO.

### ISSUE THREAD

**Issue by BrokenPencil223** [m-x-d/GZDoom-Builder#6]
More specifically; I created the ZDoom MAPINFO in Slade, then tried to edit it in GZDoom builder. Attempting to save afterwards resulted in the following crash:

***********SYSTEM INFO***********
OS: Microsoft Windows 7 Ultimate 
GPU: Intel(R) HD Graphics
GZDB: R2787

********EXCEPTION DETAILS********
Object reference not set to an instance of an object.
   at CodeImp.DoomBuilder.IO.WAD.WriteHeaders() in x:\Source\Core\IO\WAD.cs:line 297
   at CodeImp.DoomBuilder.IO.WAD.RemoveAt(Int32 index) in x:\Source\Core\IO\WAD.cs:line 458
   at CodeImp.DoomBuilder.Data.WADReader.SaveFile(MemoryStream lumpdata, String lumpname, Int32 lumpindex) in x:\Source\Core\Data\WADReader.cs:line 1159
   at CodeImp.DoomBuilder.Controls.ScriptResourceDocumentTab.Save() in x:\Source\Core\Controls\Scripting\ScriptResourceDocumentTab.cs:line 119
   at CodeImp.DoomBuilder.Controls.ScriptEditorPanel.SaveScript(ScriptDocumentTab t) in x:\Source\Core\Controls\Scripting\ScriptEditorPanel.cs:line 1694
   at CodeImp.DoomBuilder.Controls.ScriptEditorPanel.buttonsave_Click(Object sender, EventArgs e) in x:\Source\Core\Controls\Scripting\ScriptEditorPanel.cs:line 1648
   at CodeImp.DoomBuilder.Controls.ScriptEditorPanel.ExplicitSaveCurrentTab() in x:\Source\Core\Controls\Scripting\ScriptEditorPanel.cs:line 1432
   at CodeImp.DoomBuilder.Controls.ScriptEditorControl.ProcessCmdKey(Message& msg, Keys keydata) in x:\Source\Core\Controls\Scripting\ScriptEditorControl.cs:line 964
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

This has happened a couple times before.

**Comment by buu342** [comment]
I get the same issue when modifying the Decorate. Running x64, latest beta version of GZDB.
